"""Qualitative error-case table (port of ``11_error_examples``). No new compute.

Selects real error items (feminine gold, every model prefers the masculine
foil) for T6 and T3 directly from ``behavioral_results.csv``, and assembles
the Arabic sentence, verb forms, cue word, and English glosses from
``families.jsonl`` and ``lexicon.json`` -- nothing is hand-authored, so the
table always matches the committed data. Emits ``data/error_examples.tex``
and a markdown preview for a native-speaker check.
"""

from __future__ import annotations

import json
import os

import pandas as pd

from cuewin.config import data_dir

PREP_EN = {"مع": "with", "أمام": "in-front-of", "بجوار": "next-to"}
MODEL_LABEL = {"arabert": "AraBERT", "camelbert": "CAMeLBERT", "arbert": "ARBERT"}
N_SHOW = 2            # rows per condition
MIN_MODELS_WRONG = 3  # keep only items every model gets wrong


def _load(base):
    fam = {it["id"]: it for it in
           (json.loads(l) for l in open(os.path.join(base, "families.jsonl"),
                                        encoding="utf-8"))}
    lex = json.load(open(os.path.join(base, "lexicon.json"), encoding="utf-8"))
    gloss = {}
    for section in ("subjects", "adjectives", "attractors"):
        for r in lex[section]:
            gloss[r["masc"]] = r["gloss"]
    for r in lex["names"]:
        gloss[r["masc"]] = str(r.get("gloss", r["masc"])).split("/")[0]
    comp_en = {f["masc"]: " ".join(str(f["gloss"]).split()[1:])
               for f in lex["vp_frames"]}
    beh = pd.read_csv(os.path.join(base, "behavioral_results.csv"))
    beh["wrong"] = ~beh["correct"]
    return fam, gloss, comp_en, beh


def pick_items(cond, fam, beh):
    fem_ids = [i for i, it in fam.items()
               if it["condition"] == cond and it["gold"] == "f"]
    sub = beh[beh.id.isin(fem_ids)].groupby("id").agg(
        n_wrong=("wrong", "sum"), margin=("logit_diff", "mean"))
    sub = sub[sub.n_wrong >= MIN_MODELS_WRONG].sort_values("margin")
    return list(sub.index[:N_SHOW])


def describe(iid, fam, gloss, comp_en, beh):
    it = fam[iid]
    L = it["lex"]
    parts = [f"the~{L.get('subj_gloss', '?')}(\\textsc{{f}})"]
    if it["condition"] == "T6":
        prep = L.get("attr_prep") or next(p for p in PREP_EN if p in it["clean"])
        cue_word = L.get("attr_masc")
        cue_kind = "attractor"
        cue_gloss = gloss.get(cue_word, "?").split("/")[0]
        parts += [PREP_EN.get(prep, prep), f"{cue_gloss}(\\textsc{{m}})"]
    else:
        cue_word = L.get("adj_masc")
        cue_kind = "adjective"
        cue_gloss = gloss.get(cue_word, "?")
        parts.append(f"the-{cue_gloss}(\\textsc{{m}})")
    parts.append(f"[\\_\\_] {comp_en.get(L.get('verb_masc'), '')}")
    wrong = sorted(beh[(beh.id == iid) & beh.wrong]["model"])
    return dict(id=iid, cond=it["condition"], arabic=it["clean"],
                gloss=" ".join(parts), gold=it["gold_form"],
                foil=it["foil_form"], cue_kind=cue_kind, cue_word=cue_word,
                cue_gloss=cue_gloss, models_wrong=wrong)


def main():
    base = data_dir()
    fam, gloss, comp_en, beh = _load(base)
    rows = []
    for cond in ("T6", "T3"):
        for iid in pick_items(cond, fam, beh):
            rows.append(describe(iid, fam, gloss, comp_en, beh))

    lines = [
        "% Qualitative error cases, generated by cuewin-error-examples from",
        "% families.jsonl + behavioral_results.csv + lexicon.json.",
        "% Every row is a real benchmark item; the parenthetical lists the",
        "% encoders whose forced choice prefers the masculine foil.",
        "\\begin{table*}[t]\\centering\\small",
        "\\begin{tabular}{llll}",
        "\\toprule",
        "Cond. & Item id & Sentence (gloss); gold \\emph{fem.} vs. masc. foil & Winning cue \\\\",
        "\\midrule",
    ]
    for r in rows:
        sent = (f"{r['arabic'].replace('[MASK]', '\\rule{6mm}{0.4pt}')}\\newline "
                f"{r['gloss']}\\newline "
                f"gold \\emph{{fem.}}~{r['gold']} vs. \\emph{{masc.}}~{r['foil']} "
                f"({', '.join(MODEL_LABEL[m] for m in r['models_wrong'])})")
        winning = f"{r['cue_word']} ({r['cue_kind']}, \\textsc{{m}}; '{r['cue_gloss']}')"
        lines.append(f"{r['cond']} & \\texttt{{{r['id']}}} & {sent} & {winning} \\\\")
        lines.append("\\addlinespace")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Real agreement errors. In every case the subject is feminine, so the "
        "gold verb carries the feminine suffix; every encoder instead prefers the "
        "masculine form under two-candidate forced choice, agreeing with an intervening "
        "masculine cue (a recency \\emph{attractor} in T6, a conflicting "
        "\\emph{adjective} in T3). Glosses: \\textsc{m}/\\textsc{f} = grammatical "
        "gender.}",
        "\\label{tab:errors}",
        "\\end{table*}",
    ]
    out_tex = os.path.join(base, "error_examples.tex")
    open(out_tex, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"saved {out_tex}\n")

    print("### PREVIEW - please sanity-check the Arabic & glosses\n")
    for r in rows:
        print(f"* **[{r['id']}] ({r['cond']})** {r['arabic']}")
        print(f"  - Gloss: {r['gloss']}")
        print(f"  - Gold (fem): {r['gold']}  |  Masc. foil: {r['foil']}"
              f"  |  Wrong: {', '.join(r['models_wrong'])}")
        print(f"  - Winning cue: {r['cue_word']} ({r['cue_kind']}; '{r['cue_gloss']}')")
        print()


if __name__ == "__main__":
    main()
